# Generated by Django 5.2.5 on 2025-08-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentwork',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='recentwork',
            name='video_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
