# Generated by Django 5.2.5 on 2025-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_recentwork_youtube_url_recentwork_video_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
