# Generated by Django 5.2.5 on 2025-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contactform_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='contact_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('consultancy', 'Consultancy')], default='contact', max_length=20),
        ),
    ]
