# Generated by Django 5.2.5 on 2025-09-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_contactform_contact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZitaashiStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=250)),
                ('image_type', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='studio')),
            ],
        ),
    ]
