# Generated by Django 5.2.5 on 2025-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_zitaashistudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zitaashistudio',
            name='image_type',
            field=models.CharField(choices=[('banner', 'Banner'), ('sub_banner', 'Sub Banner'), ('studio_tour', 'Studio Tour')], max_length=20),
        ),
    ]
